messai-engineering/Yuga

pom.xml, src/main/java/com/twelfthmile/yuga/utils/Constants.java
Added new dateFormatter akin to dateTimeFormatter in Yuga.Constants
Upgraded jackson to fix security vulnerability
=> New DateFormatter and Security Fix

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java, src/main/java/com/twelfthmile/yuga/utils/FsaContextMap.java, src/test/java/com/twelfthmile/yuga/YugaTest.java
Bug where word came after IST date fixed "Wed Jan 01 13:00:45 IST 2020 t"
=> Yuga to support years till 1971

src/main/java/com/twelfthmile/yuga/Yuga.java, src/main/java/com/twelfthmile/yuga/utils/Constants.java, src/main/java/com/twelfthmile/yuga/utils/Util.java, src/test/resources/yuga_tests.json
-  Added Support for NonEnglish Month and day support 
- Known issues resolved
- Test cases added
=> YugaV33 || NonEnglish Month and day support || Fixes

src/main/java/com/twelfthmile/yuga/Yuga.java, src/test/resources/yuga_tests.json
Handle NumDay range like 1-2 days where 1-2 was becoming 1 feb.
=> YugaV34 || Handle Num Day range

src/main/java/com/twelfthmile/yuga/Yuga.java, src/main/java/com/twelfthmile/yuga/utils/Util.java, src/test/resources/yuga_tests.json
Detect time like 5 am or 6 pm.
Convert 5000/- to AMT based on prefix
=> YugaV35 || NUM to AMT || DETECT H AM/PM

src/main/java/com/twelfthmile/yuga/Yuga.java, src/test/resources/yuga_tests.json
3-4 becomes date in yuga. If followed by suffix like business day or working day or day , It should not resolve to a DATE
=> YugaV37 || fix 3-4 day glitch

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java, src/main/java/com/twelfthmile/yuga/utils/Constants.java, src/main/java/com/twelfthmile/yuga/utils/Util.java, src/test/resources/yuga_tests.json
IL-190 : Corrected date captured incorrectly [ Correct date is June'2018 but it is captured as June'2012]
IL-198: Ton appears as Rupees in Reminders and Infocard
=> YugaV38 || Fixed IL ticket bugs

pom.xml
Bumped the Yuga version in pom file.
=> YugaV40 || Bumped Yuga version in pom.xml

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java, src/main/java/com/twelfthmile/yuga/utils/Constants.java
Texthighlighting fixes ||  Introducing type NUMRANGE (10-15)
=> YugaV41 || TextHighlighting fixes

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java, src/main/java/com/twelfthmile/yuga/utils/Util.java, src/test/java/com/twelfthmile/yuga/GetOutputTest.java, src/test/resources/yuga_tests.json
Fix case "11/01/2021:10:09:47 AM" where date string misses AM or PM.
=> YugaV45 || Fix NG Regression

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java, src/main/java/com/twelfthmile/yuga/utils/Constants.java, src/main/java/com/twelfthmile/yuga/utils/Util.java, src/test/java/com/twelfthmile/yuga/GetOutputTest.java, src/test/java/com/twelfthmile/yuga/YugaTest.java, src/test/resources/yuga_tests.json
Handle ranges for Day,dates and time like
TIME RANGE ex: 17:20 - 18:20
19:30 PM
24-48 hrs
10-15 Jan
1-2 Days, 3-4 working days, 2-3 business days
=> YugaV46 || Handle Ranges

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java, src/main/java/com/twelfthmile/yuga/utils/Util.java, src/test/java/com/twelfthmile/yuga/GetOutputTest.java, src/test/resources/yuga_tests.json
=> YugaV46 || Base Ranges on msgDate

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java, src/main/java/com/twelfthmile/yuga/utils/Constants.java, src/main/java/com/twelfthmile/yuga/utils/Util.java
Cases like idag kl 12-16
mellan kl 18-22
IDAG 08:00-17:00
leveranstid imorgon 10-16
=> YugaV49 || TimeRange Support for sweden

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java, src/main/java/com/twelfthmile/yuga/utils/Constants.java, src/main/java/com/twelfthmile/yuga/utils/FsaContextMap.java, src/main/java/com/twelfthmile/yuga/utils/Util.java, src/test/resources/yuga_tests.json
PHN and CALLFRWRD type introduced || IL bugs
=> YugaV55 || PHN and CALLFRWRD type introduced || IL bugs

src/main/java/com/twelfthmile/yuga/Yuga.java
Moving CallFRWRD detection outside
=> YugaV55 || Moving CallFRWRD detection

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java, src/main/java/com/twelfthmile/yuga/utils/Constants.java, src/main/java/com/twelfthmile/yuga/utils/Util.java, src/test/resources/yuga_tests.json
ISD code detection to improve PHN detection
=> YugaV56 || PHN detection improvements

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java
For IL-748: "914435 ( Rs 421.0"   - 914435 becomes AMT
=> YugaV1.61 || IlTicket Changes

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java
Updating for failing test case
=> YugaV1.62 || Test Case update

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java
Updated Yuga version to 1.0.65.
=> YugaV65 || Fix for IL-799

pom.xml, src/main/java/com/twelfthmile/yuga/Yuga.java
String index out of bounds exception at many places in Yuga.
Ticket : https://truecaller.atlassian.net/browse/IL-803
=> YugaV66 || SIIOB changes
